### ISSUE TITLE
test with db on github actions

### ISSUE THREAD

**Issue by arnfinn** [mong/imongr#98]
Testing with github actions is not done with database running. Thus, a lot of the code is not tested.

Test coverage decreased from 75 % to 34 % after going from Travis CI (with database) to Github Actions: https://app.codecov.io/gh/mong/imongr.

Some of the setup used on Travis CI:

```yaml
env:
  global:
    - IMONGR_DB_HOST="127.0.0.1"
    - IMONGR_DB_NAME="testdb"
    - IMONGR_DB_USER="travis"
    - IMONGR_DB_PASS=""

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS testdb CHARACTER SET = 'utf8' COLLATE = 'utf8_danish_ci';"
```
